### ISSUE TITLE
RAP Feedback

### ISSUE THREAD

**Issue by foster999** [b-rodrigues/rap4mads#2]
Hey Bruno,

I'm one of the authors of the [UK analysis function guidance for RAP (aka The Duck Book)](https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html).

A colleague pointed me to your bookdown earlier today. Coming from an academic background, it's really exciting to see RAP being applied to science and research outside of our immediate contacts. I'd love to chat sometime, particularly if you have any reflections on which RAP practices have worked well in your work or feedback on the analysis function resources that you have come across.

Cheers,
David

**Comment by b-rodrigues** [comment]
Hi David

let's have a call next week, I think it would be easier 😊

here's my email : bruno@brodrigues.co send me some slots that suit you and I'll send you an invite

Cheers
